### ISSUE TITLE
Is pht going to be revived?

### ISSUE THREAD

**Issue by Girgias** [tpunt/pht#11]
Hello, I am mainly asking as we are a bit in a php.net documentation conundrum.

One of our QA scripts is failing as the extension does not have a membership tag in ``book.xml``, this tag is used to generate the following page https://www.php.net/manual/en/extensions.membership.php.

Adding the ``<?phpdoc extension-membership="pecl" ?>`` seem rather unwise as the extension is not available on PECL.

As the extension seems to only works on PHP 7.2 and be unmaintained our plan is to remove the docs from the php.net website.

This mainly serves as a notice.

Best regards,

**Comment by tpunt** [comment]
Thanks for the heads-up. Given my lack of free time right now, I don't plan on working on this project in the near future. If/when I do revisit the project, then I can look to get it added back to the docs. Thanks!
