### ISSUE TITLE
no-joined thread leads to high cpu usage

### ISSUE THREAD

**Issue by zhaoyanliang8** [tpunt/pht#7]
If the parent thread forget to join the child thread, or too busy to join (and child thread finish task quickly), or even does not plan to join, then, the child thread leads to high cpu usage.

```php
<?php
use pht\Thread;

$thread = new Thread;
$thread->addFunctionTask('task');
$thread->start();
sleep(10000);

function task()
{
	sleep(1);
}
```

I debugged it and found it here.
https://github.com/tpunt/pht/blob/d79019cf96d0ff0f7389382148ef6ffc70b761e8/src/classes/thread.c#L278
After the child thread has executed all the tasks, it will cause this problem if it has not been joined yet.

By the way, are you still going to continue to maintain this project? @tpunt

**Comment by tpunt** [comment]
This is a known issue (#6) - I just haven't had the time to resolve it yet.

As for the future of this project, that is currently unknown. There's some issues with this extension, and I don't have the time to look into resolving them currently. Perhaps you should look into [parallel](https://github.com/krakjoe/parallel) for your multithreading needs? It looks like Joe has done a pretty good job on it so far, and he is actively developing it too.
