### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by feamsr00** [tpunt/pht#8]
Hi!

Quick question. Is there a notion that this will be built for 7.3 at all?

There are some nice paradigms here and it would be _interesting_ to have this out there with ~~pthreads~~[parallel](https://github.com/krakjoe/parallel).

**Comment by feamsr00** [comment]
As a reference, this is emitted on simple compilation of the existing code when targeting 7.3:
```
ext\pht\pht.c(53): error C2106: '|=': left operand must be l-value
ext\pht\pht.c(56): error C2106: '|=': left operand must be l-value
ext\pht\pht.c(59): error C2106: '|=': left operand must be l-value
ext\pht\pht.c(62): error C2106: '|=': left operand must be l-value
ext\pht\pht.c(65): error C2106: '|=': left operand must be l-value
ext\pht\pht.c(68): error C2106: '|=': left operand must be l-value
ext\pht\pht.c(71): error C2106: '|=': left operand must be l-value
ext\pht\pht.c(74): error C2106: '|=': left operand must be l-value
ext\pht\pht.c(84): error C2106: '&=': left operand must be l-value
ext\pht\pht.c(86): error C2106: '&=': left operand must be l-value
ext\pht\pht.c(88): error C2106: '&=': left operand must be l-value
ext\pht\pht.c(90): error C2106: '&=': left operand must be l-value
ext\pht\pht.c(92): error C2106: '&=': left operand must be l-value
ext\pht\pht.c(94): error C2106: '&=': left operand must be l-value
ext\pht\pht.c(96): error C2106: '&=': left operand must be l-value
ext\pht\pht.c(98): error C2106: '&=': left operand must be l-value
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe"' : return code '0x2'
Stop.
```
From https://github.com/tpunt/pht/blob/master/pht.c#L53-L98

**Comment by tpunt** [comment]
Unfortunately, I just haven't had the time (and still don't have the time) to maintain my open source projects. I hope to come back to them in the near future (especially my projects related to exploring concurrency in PHP), but that likely won't be until later this year. Maybe I'll try to make a release that coincides with PHP 7.4.

**Comment by irisism4you** [comment]
Very hope for it. Good multithreading is very needed... and your simple API library looks very interesting.

**Comment by BlackCatDevel0per** [comment]
> Very hope for it. Good multithreading is very needed... and your simple API library looks very interesting.

Try pthreads fork [ext-pmmpthread](https://github.com/pmmp/ext-pmmpthread) from Pocketmine-MP project)

**Comment by feamsr00** [comment]
> > Very hope for it. Good multithreading is very needed... and your simple API library looks very interesting.
> 
> Try pthreads fork [ext-pmmpthread](https://github.com/pmmp/ext-pmmpthread) from Pocketmine-MP project)

I'll close this as stale as we're on PHP 8+ already and ext-pmmpthread seems very interesting.

Vaya con Dios PHT
